<?php
// Pastikan path koneksi ke database sudah benar
require_once 'config/koneksi.php';

// --- PENTING: INCLUDE FILE TCPDF ---
// Sesuaikan path ini dengan lokasi file tcpdf.php Anda
require_once('tcpdf/tcpdf.php');

// --- 1. LOGIKA DATA (Sama seperti rekap_validasi.php) ---

$instrumen = [
    'A. Aspek Kelayakan Media' => [
        'Ketersediaan fitur interaktif yang menunjang pembelajaran.',
        'Kualitas tampilan visual (warna, font, tata letak) yang menarik dan jelas.',
        'Kemudahan navigasi antar halaman/menu (user-friendly).',
        'Stabilitas dan kinerja media saat diakses.'
    ],
    'B. Aspek Kelayakan Materi' => [
        'Kesesuaian materi dengan Kurikulum dan Kompetensi Dasar (KD) yang ditargetkan.',
        'Ketepatan dan kebenaran konsep-konsep matematika yang disajikan.',
        'Adanya contoh dan latihan soal yang relevan dengan kehidupan nyata (kontekstual).'
    ],
    'C. Aspek Kebahasaan' => [
        'Penggunaan bahasa yang baku dan mudah dipahami oleh siswa.',
        'Ketepatan ejaan, tata bahasa, dan istilah matematika.'
    ]
];

// 1. AMBIL DATA AHLI (Untuk Ringkasan)
$query_ahli = "SELECT DISTINCT nama_ahli, bidang_ahli, instansi, kesimpulan_umum, tanggal_review FROM hasil_validasi ORDER BY tanggal_review DESC";
$result_ahli = $db_mapel->query($query_ahli);
$jumlah_ahli = $result_ahli->num_rows;

// 2. HITUNG RATA-RATA SKOR KESELURUHAN
$query_rata_global = "SELECT AVG(skor_penilaian) as rata_rata_skor FROM hasil_validasi";
$result_rata_global = $db_mapel->query($query_rata_global);
$data_rata_global = $result_rata_global->fetch_assoc();
$rata_rata_skor_global = $data_rata_global['rata_rata_skor'] ?? 0;
$persentase_kelayakan = ($rata_rata_skor_global / 5) * 100;

function getKategori($skor) {
    if ($skor >= 4.5) return "Sangat Baik";
    if ($skor >= 3.5) return "Baik";
    if ($skor >= 2.5) return "Cukup";
    if ($skor >= 1.5) return "Kurang";
    return "Sangat Kurang";
}

$kategori_kelayakan = getKategori($rata_rata_skor_global);

// 3. HITUNG RATA-RATA SKOR PER INDIKATOR
$rata_rata_per_indikator = [];
$no_indikator = 1;
foreach ($instrumen as $aspek => $indikator_list) {
    foreach ($indikator_list as $indikator) {
        $query_rata_indikator = "SELECT AVG(skor_penilaian) as rata_rata FROM hasil_validasi WHERE indikator = ?";
        $stmt = $db_mapel->prepare($query_rata_indikator);
        $stmt->bind_param("s", $indikator);
        $stmt->execute();
        $result = $stmt->get_result();
        $data = $result->fetch_assoc();

        $skor = $data['rata_rata'] ?? 0;

        $rata_rata_per_indikator[] = [
            'no' => $no_indikator++,
            'aspek' => $aspek,
            'indikator' => $indikator,
            'rata_rata' => $skor > 0 ? number_format($skor, 2) : 'N/A',
            'kategori' => $skor > 0 ? getKategori($skor) : '-'
        ];
        $stmt->close();
    }
}

// 4. Catatan Saran Detail
$query_detail_catatan = "SELECT nama_ahli, indikator, catatan_saran, kesimpulan_umum FROM hasil_validasi WHERE catatan_saran IS NOT NULL AND catatan_saran != '' OR kesimpulan_umum IS NOT NULL GROUP BY nama_ahli, indikator, catatan_saran ORDER BY nama_ahli, id ASC";
$result_detail_catatan = $db_mapel->query($query_detail_catatan);

$catatan_per_ahli = [];
while ($row = $result_detail_catatan->fetch_assoc()) {
    $nama = $row['nama_ahli'];
    if (!isset($catatan_per_ahli[$nama])) {
        // Ambil kesimpulan umum hanya sekali per ahli
        $catatan_per_ahli[$nama]['kesimpulan_umum'] = $row['kesimpulan_umum'];
        $catatan_per_ahli[$nama]['detail_saran'] = [];
    }
    if (!empty($row['catatan_saran'])) {
        $catatan_per_ahli[$nama]['detail_saran'][] = [
            'indikator' => $row['indikator'],
            'saran' => $row['catatan_saran']
        ];
    }
}
$result_ahli->data_seek(0); // Reset pointer ahli
// --- AKHIR LOGIKA DATA ---


// --- 2. GENERASI PDF MENGGUNAKAN TCPDF ---

// Buat objek PDF baru
// 'P' = Portrait, 'mm' = unit, 'A4' = format kertas, true = unicode, 'UTF-8' = encoding
$pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

// Atur informasi dokumen
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('Sistem Validasi Media');
$pdf->SetTitle('Laporan Rekapitulasi Validasi Media');
$pdf->SetSubject('Hasil Penilaian Ahli');
$pdf->SetKeywords('PDF, Laporan, Validasi, Media');

// Atur header dan footer (opsional, bisa dihilangkan)
$pdf->SetHeaderData(PDF_HEADER_LOGO, PDF_HEADER_LOGO_WIDTH, 'LAPORAN REKAPITULASI VALIDASI MEDIA', 'Generated by: ' . date('d/m/Y H:i:s'));
$pdf->setFooterData(array(0,64,0), array(0,64,128));

// Atur margin
$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

// Atur pemecahan halaman otomatis
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

// Atur rasio faktor scaling gambar
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

// Tambahkan halaman baru
$pdf->AddPage();

// --- Konten PDF dalam format HTML ---
$html = '
<style>
    h1 { color: #007bff; text-align: center; font-size: 16pt; }
    h2 { color: #28a745; border-bottom: 1px solid #ccc; padding-bottom: 5px; font-size: 14pt; }
    h3 { color: #dc3545; font-size: 12pt; margin-top: 15px; }
    .summary-box { border: 1px solid #ddd; padding: 10px; margin-bottom: 15px; background-color: #f8f9fa; }
    table { width: 100%; border-collapse: collapse; margin-top: 10px; }
    th, td { border: 1px solid #333; padding: 5px; font-size: 9pt; vertical-align: top; }
    th { background-color: #e9ecef; text-align: center; font-weight: bold; }
    .aspek-header { background-color: #add8e6; color: #333; font-weight: bold; text-align: left; }
    .blockquote { border-left: 3px solid #007bff; padding-left: 10px; margin: 10px 0; }
    ul { list-style-type: none; padding: 0; }
    li { margin-bottom: 5px; }
</style>
<h1>LAPORAN REKAPITULASI VALIDASI MEDIA MATFICTION</h1>
<p style="text-align: center;">Tanggal Pencetakan: ' . date('d F Y') . '</p>

<h2>Ringkasan Kelayakan Global</h2>
<p>Total Ahli: <strong>' . $jumlah_ahli . '</strong></p>
<p>Rata-rata Skor Keseluruhan: <strong>' . number_format($rata_rata_skor_global, 2) . '</strong> (dari maks. 5)</p>
<p>Kategori Kelayakan: <span style="font-weight: bold; color: ' . ($kategori_kelayakan == "Sangat Baik" ? '#28a745' : '#ffc107') . ';">' . $kategori_kelayakan . '</span></p>
<p>Persentase Kelayakan: <strong>' . number_format($persentase_kelayakan, 2) . '%</strong></p>

<h2>Rata-rata Penilaian Per Indikator</h2>
<table>
    <thead>
        <tr>
            <th style="width: 5%;">No.</th>
            <th style="width: 50%;">Indikator Penilaian</th>
            <th style="width: 25%;">Rata-rata Skor</th>
            <th style="width: 20%;">Kategori</th>
        </tr>
    </thead>
    <tbody>';

$current_aspek = '';
foreach ($rata_rata_per_indikator as $item) {
    if ($current_aspek != $item['aspek']) {
        $current_aspek = $item['aspek'];
        $html .= '<tr><td colspan="4" class="aspek-header">' . htmlspecialchars($item['aspek']) . '</td></tr>';
    }
    $html .= '
        <tr>
            <td style="text-align: center;">' . $item['no'] . '.</td>
            <td>' . htmlspecialchars($item['indikator']) . '</td>
            <td style="text-align: center;">' . $item['rata_rata'] . '</td>
            <td style="text-align: center;">' . $item['kategori'] . '</td>
        </tr>';
}

$html .= '
    </tbody>
</table>

<h2>Catatan dan Saran Ahli</h2>';

if ($jumlah_ahli > 0) {
    // Tampilkan data ahli dari hasil query awal
    $result_ahli->data_seek(0);
    $ahli_counter = 1;
    while ($ahli = $result_ahli->fetch_assoc()) {
        $nama_ahli = htmlspecialchars($ahli['nama_ahli']);
        $bidang_ahli = htmlspecialchars($ahli['bidang_ahli']);
        $kesimpulan_umum = !empty($ahli['kesimpulan_umum']) ? nl2br(htmlspecialchars($ahli['kesimpulan_umum'])) : 'Tidak ada kesimpulan umum yang dicatat.';
        $tanggal_review = date("d M Y", strtotime($ahli['tanggal_review']));

        $html .= '
        <h3>' . $ahli_counter . '. ' . $nama_ahli . ' (' . $bidang_ahli . ')</h3>
        <p><strong>Kesimpulan Umum/Saran Akhir:</strong></p>
        <div class="blockquote">' . $kesimpulan_umum . '</div>';

        // Tampilkan saran detail per indikator
        if (!empty($catatan_per_ahli[$ahli['nama_ahli']]['detail_saran'])) {
            $html .= '<p><strong>Saran Detail per Indikator:</strong></p><ul>';
            foreach ($catatan_per_ahli[$ahli['nama_ahli']]['detail_saran'] as $detail) {
                $html .= '<li><strong>[' . htmlspecialchars($detail['indikator']) . ']</strong>: ' . nl2br(htmlspecialchars($detail['saran'])) . '</li>';
            }
            $html .= '</ul>';
        } else {
            $html .= '<p>Tidak ada saran detail yang dicatat untuk ahli ini.</p>';
        }
        $html .= '<p style="font-size: 8pt; text-align: right;">Tanggal Review: ' . $tanggal_review . '</p><hr>';
        $ahli_counter++;
    }
} else {
    $html .= '<p style="color: red;">Belum ada data validasi yang tersimpan.</p>';
}

$pdf->writeHTML($html, true, false, true, false, '');

// --- 3. OUTPUT PDF ---
// 'I' = Inline (tampil di browser), 'D' = Download, 'F' = Save to file
$pdf->Output('Laporan_Validasi_Media_' . date('Ymd_His') . '.pdf', 'I');

exit;
?>